<?php

if (!defined('ABSPATH')) die('-1');

class WpGradeShortcode_Icon extends  WpGradeShortcode {

    public function __construct($settings = array()) {
        $this->self_closed = true;
        $this->name = "Icon";
        $this->code = "icon";
        $this->icon = "icon-magic";
        $this->direct = false;

        $this->backend_assets["js"] = array(
            "icons" => array(
                'name' => 'icons',
                'path' => 'js/shortcodes/backend_icons.js',
                'deps'=> array( 'jquery' )
            )
        );

        // load backend assets only when an editor is present
        add_action( 'mce_buttons_2', array( $this, 'load_backend_assets' ) );

        $this->params = array(
            'type' => array(
                'type' => 'select',
                'name' => 'Background Shape',
                'options' => array('' => '-- Select Type --', 'circle' => 'Circle', 'rectangle' => 'Rectangle'),
                'admin_class' => 'span6'
            ),
            'size' => array(
                'type' => 'select',
                'name' => 'Icon Size',
                'options' => array('' => '-- Select Size --', 'small' => 'Small', 'medium' => 'Medium', 'big' => 'Big'),
                'admin_class' => 'span5 push1'
            ),
	        'class' => array(
		        'type' => 'tags',
		        'name' => 'Custom CSS Class',
		        'admin_class' => 'span12',
		        'options' => array('icon-border', 'pull-right', 'pull-left', 'icon-spin', 'icon-rotate-90', 'icon-rotate-180', 'icon-rotate-270', 'icon-flip-horizontal', 'icon-flip-vertical', 'icon-2x', 'icon-3x', 'icon-4x' ),
		        'value' => array( '' )
	        ),
            'name'=> array(
              'type'=> 'icon_list',
              'name' => 'Select icon:',
              'icons' => array(
                  //Entypo
                  "e-plus",     
                  "e-minus",    
                  "e-fivehundredpx",     
                  "e-digg",
                  "e-cc-1",
                  "e-dribbble-1",
                  "e-youtube",
                  "e-googleplay",
                  "e-soundcloud-1",
                  "e-appnet",
                  "e-info",
                  "e-left-thin",
                  "e-up-thin",
                  "e-right-thin",
                  "e-down-thin",
                  "e-level-up",
                  "e-level-down",
                  "e-switch",
                  "e-infinity",
                  "e-plus-squared",
                  "e-minus-squared",
                  "e-home",
                  "e-keyboard",
                  "e-erase",
                  "e-pause",
                  "e-fast-forward",
                  "e-fast-backward",
                  "e-to-end",
                  "e-to-start",
                  "e-hourglass",
                  "e-stop-1",
                  "e-up-dir",
                  "e-play",
                  "e-right-dir",
                  "e-down-dir",
                  "e-left-dir",
                  "e-adjust",
                  "e-cloud",
                  "e-star",
                  "e-star-empty",
                  "e-cup",
                  "e-menu",
                  "e-moon",
                  "e-heart-empty",
                  "e-heart",
                  "e-note",
                  "e-note-beamed",
                  "e-layout",
                  "e-flag",
                  "e-tools",
                  "e-cog",
                  "e-attention",
                  "e-flash",
                  "e-record",
                  "e-cloud-thunder",
                  "e-tape",
                  "e-flight",
                  "e-mail",
                  "e-pencil",
                  "e-feather",
                  "e-check",
                  "e-cancel",
                  "e-cancel-circled",
                  "e-cancel-squared",
                  "e-help",
                  "e-quote",
                  "e-plus-circled",
                  "e-minus-circled",
                  "e-right",
                  "e-direction",
                  "e-forward",
                  "e-ccw",
                  "e-cw",
                  "e-left",
                  "e-up",
                  "e-down",
                  "e-list-add",
                  "e-list",
                  "e-deviantart",
                  "e-left-bold",
                  "e-right-bold",
                  "e-up-bold",
                  "e-down-bold",
                  "e-user-add",
                  "e-help-circled",
                  "e-info-circled",
                  "e-eye",
                  "e-tag",
                  "e-upload-cloud",
                  "e-reply",
                  "e-reply-all",
                  "e-code",
                  "e-export",
                  "e-print",
                  "e-retweet",
                  "e-comment",
                  "e-chat",
                  "e-vcard",
                  "e-address",
                  "e-location",
                  "e-map",
                  "e-compass",
                  "e-trash",
                  "e-doc",
                  "e-doc-text-inv",
                  "e-docs",
                  "e-doc-landscape",
                  "e-archive",
                  "e-rss",
                  "e-share",
                  "e-basket",
                  "e-shareable",
                  "e-login",
                  "e-logout",
                  "e-volume",
                  "e-resize-full",
                  "e-resize-small",
                  "e-popup",
                  "e-publish",
                  "e-window",
                  "e-arrow-combo",
                  "e-chart-pie",
                  "e-language",
                  "e-air",
                  "e-database",
                  "e-drive",
                  "e-bucket",
                  "e-thermometer",
                  "e-down-circled",
                  "e-left-circled",
                  "e-right-circled",
                  "e-up-circled",
                  "e-down-open",
                  "e-left-open",
                  "e-right-open",
                  "e-up-open",
                  "e-down-open-mini",
                  "e-left-open-mini",
                  "e-right-open-mini",
                  "e-up-open-mini",
                  "e-down-open-big",
                  "e-left-open-big",
                  "e-right-open-big",
                  "e-up-open-big",
                  "e-progress-0",
                  "e-progress-1",
                  "e-progress-2",
                  "e-progress-3",
                  "e-back-in-time",
                  "e-network",
                  "e-inbox",
                  "e-install",
                  "e-lifebuoy",
                  "e-mouse",
                  "e-dot",
                  "e-dot-2",
                  "e-dot-3",
                  "e-suitcase",
                  "e-flow-cascade",
                  "e-flow-branch",
                  "e-flow-tree",
                  "e-flow-line",
                  "e-flow-parallel",
                  "e-brush",
                  "e-paper-plane",
                  "e-magnet",
                  "e-gauge",
                  "e-traffic-cone",
                  "e-cc",
                  "e-cc-by",
                  "e-cc-nc",
                  "e-cc-nc-eu",
                  "e-cc-nc-jp",
                  "e-cc-sa",
                  "e-cc-nd",
                  "e-cc-pd",
                  "e-cc-zero",
                  "e-cc-share",
                  "e-cc-remix",
                  "e-github",
                  "e-github-circled",
                  "e-flickr",
                  "e-flickr-circled",
                  "e-vimeo",
                  "e-vimeo-circled",
                  "e-twitter",
                  "e-twitter-circled",
                  "e-facebook",
                  "e-facebook-circled",
                  "e-facebook-squared",
                  "e-gplus",
                  "e-gplus-circled",
                  "e-pinterest",
                  "e-pinterest-circled",
                  "e-tumblr",
                  "e-tumblr-circled",
                  "e-linkedin",
                  "e-linkedin-circled",
                  "e-dribbble",
                  "e-dribbble-circled",
                  "e-stumbleupon",
                  "e-stumbleupon-circled",
                  "e-lastfm",
                  "e-lastfm-circled",
                  "e-rdio",
                  "e-rdio-circled",
                  "e-spotify",
                  "e-spotify-circled",
                  "e-qq",
                  "e-instagram",
                  "e-dropbox",
                  "e-evernote",
                  "e-flattr",
                  "e-skype",
                  "e-skype-circled",
                  "e-renren",
                  "e-sina-weibo",
                  "e-paypal",
                  "e-picasa",
                  "e-soundcloud",
                  "e-mixi",
                  "e-behance",
                  "e-google-circles",
                  "e-vkontakte",
                  "e-smashing",
                  "e-db-shape",
                  "e-sweden",
                  "e-logo-db",
                  "e-picture",
                  "e-globe",
                  "e-leaf",
                  "e-graduation-cap",
                  "e-mic",
                  "e-palette",
                  "e-ticket",
                  "e-video",
                  "e-target",
                  "e-music",
                  "e-trophy",
                  "e-thumbs-up",
                  "e-thumbs-down",
                  "e-bag",
                  "e-user",
                  "e-users",
                  "e-lamp",
                  "e-alert",
                  "e-water",
                  "e-droplet",
                  "e-credit-card",
                  "e-monitor",
                  "e-briefcase",
                  "e-floppy",
                  "e-cd",
                  "e-folder",
                  "e-doc-text",
                  "e-calendar",
                  "e-chart-line",
                  "e-chart-bar",
                  "e-clipboard",
                  "e-attach",
                  "e-bookmarks",
                  "e-book",
                  "e-book-open",
                  "e-phone",
                  "e-megaphone",
                  "e-upload",
                  "e-download",
                  "e-box",
                  "e-newspaper",
                  "e-mobile",
                  "e-signal",
                  "e-camera",
                  "e-shuffle",
                  "e-loop",
                  "e-arrows-ccw",
                  "e-light-down",
                  "e-light-up",
                  "e-mute",
                  "e-sound",
                  "e-battery",
                  "e-search",
                  "e-key",
                  "e-lock",
                  "e-lock-open",
                  "e-bell",
                  "e-bookmark",
                  "e-link",
                  "e-back",
                  "e-flashlight",
                  "e-chart-area",
                  "e-clock",
                  "e-rocket",
                  "e-block",
                  //Font Awesome
                  "glass",
                  "music",
                  "search",
                  "envelope",
                  "heart",
                  "star",
                  "star-empty",
                  "user",
                  "film",
                  "th-large",
                  "th",
                  "th-list",
                  "ok",
                  "remove",
                  "zoom-in",
                  "zoom-out",
                  "off",
                  "signal",
                  "cog",
                  "trash",
                  "home",
                  "file",
                  "time",
                  "road",
                  "download-alt",
                  "download",
                  "upload",
                  "inbox",
                  "play-circle",
                  "repeat",
                  "refresh",
                  "list-alt",
                  "lock",
                  "flag",
                  "headphones",
                  "volume-off",
                  "volume-down",
                  "volume-up",
                  "qrcode",
                  "barcode",
                  "tag",
                  "tags",
                  "book",
                  "bookmark",
                  "print",
                  "camera",
                  "font",
                  "bold",
                  "italic",
                  "text-height",
                  "text-width",
                  "align-left",
                  "align-center",
                  "align-right",
                  "align-justify",
                  "list",
                  "indent-left",
                  "indent-right",
                  "facetime-video",
                  "picture",
                  "pencil",
                  "map-marker",
                  "adjust",
                  "tint",
                  "edit",
                  "share",
                  "check",
                  "move",
                  "step-backward",
                  "fast-backward",
                  "backward",
                  "play",
                  "pause",
                  "stop",
                  "forward",
                  "fast-forward",
                  "step-forward",
                  "eject",
                  "chevron-left",
                  "chevron-right",
                  "plus-sign",
                  "minus-sign",
                  "remove-sign",
                  "ok-sign",
                  "question-sign",
                  "info-sign",
                  "screenshot",
                  "remove-circle",
                  "ok-circle",
                  "ban-circle",
                  "arrow-left",
                  "arrow-right",
                  "arrow-up",
                  "arrow-down",
                  "share-alt",
                  "resize-full",
                  "resize-small",
                  "plus",
                  "minus",
                  "asterisk",
                  "exclamation-sign",
                  "gift",
                  "leaf",
                  "fire",
                  "eye-open",
                  "eye-close",
                  "warning-sign",
                  "plane",
                  "calendar",
                  "random",
                  "comment",
                  "magnet",
                  "chevron-up",
                  "chevron-down",
                  "retweet",
                  "shopping-cart",
                  "folder-close",
                  "folder-open",
                  "resize-vertical",
                  "resize-horizontal",
                  "bar-chart",
                  "twitter-sign",
                  "facebook-sign",
                  "camera-retro",
                  "key",
                  "cogs",
                  "comments",
                  "thumbs-up",
                  "thumbs-down",
                  "star-half",
                  "heart-empty",
                  "signout",
                  "linkedin-sign",
                  "pushpin",
                  "external-link",
                  "signin",
                  "trophy",
                  "github-sign",
                  "upload-alt",
                  "lemon",
                  "phone",
                  "check-empty",
                  "bookmark-empty",
                  "phone-sign",
                  "twitter",
                  "facebook",
                  "github",
                  "unlock",
                  "credit-card",
                  "rss",
                  "hdd",
                  "bullhorn",
                  "bell",
                  "certificate",
                  "hand-right",
                  "hand-left",
                  "hand-up",
                  "hand-down",
                  "circle-arrow-left",
                  "circle-arrow-right",
                  "circle-arrow-up",
                  "circle-arrow-down",
                  "globe",
                  "wrench",
                  "tasks",
                  "filter",
                  "briefcase",
                  "fullscreen",
                  "group",
                  "link",
                  "cloud",
                  "beaker",
                  "cut",
                  "copy",
                  "paper-clip",
                  "save",
                  "sign-blank",
                  "reorder",
                  "list-ul",
                  "list-ol",
                  "strikethrough",
                  "underline",
                  "table",
                  "magic",
                  "truck",
                  "pinterest",
                  "pinterest-sign",
                  "google-plus-sign",
                  "google-plus",
                  "money",
                  "caret-down",
                  "caret-up",
                  "caret-left",
                  "caret-right",
                  "columns",
                  "sort",
                  "sort-down",
                  "sort-up",
                  "envelope-alt",
                  "linkedin",
                  "undo",
                  "legal",
                  "dashboard",
                  "comment-alt",
                  "comments-alt",
                  "bolt",
                  "sitemap",
                  "umbrella",
                  "paste",
                  "lightbulb",
                  "exchange",
                  "cloud-download",
                  "cloud-upload",
                  "user-md",
                  "stethoscope",
                  "suitcase",
                  "bell-alt",
                  "coffee",
                  "food",
                  "file-alt",
                  "building",
                  "hospital",
                  "ambulance",
                  "medkit",
                  "fighter-jet",
                  "beer",
                  "h-sign",
                  "plus-sign-alt",
                  "double-angle-left",
                  "double-angle-right",
                  "double-angle-up",
                  "double-angle-down",
                  "angle-left",
                  "angle-right",
                  "angle-up",
                  "angle-down",
                  "desktop",
                  "laptop",
                  "tablet",
                  "mobile-phone",
                  "circle-blank",
                  "quote-left",
                  "quote-right",
                  "spinner",
                  "circle",
                  "reply",
                  "github-alt",
                  "folder-close-alt",
                  "folder-open-alt",
                   "user",
                  "film",
                  "th-large"
                )
            )
        );

	    // allow the theme or other plugins to "hook" into this shorcode's params
	    $this->params = apply_filters('pixcodes_filter_params_for_' . strtolower($this->name), $this->params);

        add_shortcode('icon', array( $this, 'add_shortcode') );
    }

    public function add_shortcode($atts, $content){

        extract( shortcode_atts( array(
            'name' => '',
            'type' => '',
            'size' => '',
	        'class' => ''
        ), $atts ) );

		// replace the , with a space
	    $classes = explode(',',$class);
	    $class = implode(' ', $classes);
		
		// make sure that there is no icon- in front
		$prefix = 'icon-';
		if (substr($name, 0, strlen($prefix)) == $prefix) {
			$name = substr($name, strlen($prefix));
		}

	    /**
	     * Template localization between plugin and theme
	     */
	    $located = locate_template("templates/shortcodes/{$this->code}.php", false, false);
	    if(!$located) {
		    $located = dirname(__FILE__).'/templates/'.$this->code.'.php';
	    }
	    // load it
	    ob_start();
	    require $located;
	    return ob_get_clean();
    }
}
