<?php

if (!defined('ABSPATH')) die('-1');

class WpGradeShortcode_Icon extends  WpGradeShortcode {

    public function __construct($settings = array()) {
        $this->self_closed = true;
        $this->name = "Icon";
        $this->code = "icon";
        $this->icon = "icon-magic";
        $this->direct = false;

        $this->backend_assets["js"] = array(
            "icons" => array(
                'name' => 'icons',
                'path' => 'js/shortcodes/backend_icons.js',
                'deps'=> array( 'jquery' )
            )
        );

        // load backend assets only when an editor is present
        add_action( 'mce_buttons_2', array( $this, 'load_backend_assets' ) );

        $this->params = array(
            'type' => array(
                'type' => 'select',
                'name' => 'Background Shape',
                'options' => array('' => '-- Select Type --', 'circle' => 'Circle', 'rectangle' => 'Rectangle'),
                'admin_class' => 'span6'
            ),
            'size' => array(
                'type' => 'select',
                'name' => 'Icon Size',
                'options' => array('' => '-- Select Size --', 'small' => 'Small', 'medium' => 'Medium', 'big' => 'Big'),
                'admin_class' => 'span5 push1'
            ),
	        'class' => array(
		        'type' => 'tags',
		        'name' => 'Custom CSS Class',
		        'admin_class' => 'span12',
		        'options' => array('icon-border', 'pull-right', 'pull-left', 'icon-spin', 'icon-rotate-90', 'icon-rotate-180', 'icon-rotate-270', 'icon-flip-horizontal', 'icon-flip-vertical', 'icon-2x', 'icon-3x', 'icon-4x' ),
		        'value' => array( '' )
	        ),
            'name'=> array(
              'type'=> 'icon_list',
              'name' => 'Select icon:',
              'icons' => array(
                  //Entypo
                  "plus",
                  "minus",
                  "info",
                  "left-thin",
                  "up-thin",
                  "right-thin",
                  "down-thin",
                  "level-up",
                  "level-down",
                  "switch",
                  "infinity",
                  "plus-squared",
                  "minus-squared",
                  "home",
                  "keyboard",
                  "erase",
                  "pause",
                  "fast-forward",
                  "fast-backward",
                  "to-end",
                  "to-start",
                  "hourglass",
                  "stop-1",
                  "up-dir",
                  "play",
                  "right-dir",
                  "down-dir",
                  "left-dir",
                  "adjust",
                  "cloud",
                  "star",
                  "star-empty",
                  "cup",
                  "menu",
                  "moon",
                  "heart-empty",
                  "heart",
                  "note",
                  "note-beamed",
                  "layout",
                  "flag",
                  "tools",
                  "cog",
                  "attention",
                  "flash",
                  "record",
                  "cloud-thunder",
                  "tape",
                  "flight",
                  "mail",
                  "pencil",
                  "feather",
                  "check",
                  "cancel",
                  "cancel-circled",
                  "cancel-squared",
                  "help",
                  "quote",
                  "plus-circled",
                  "minus-circled",
                  "right",
                  "direction",
                  "forward",
                  "ccw",
                  "cw",
                  "left",
                  "up",
                  "down",
                  "list-add",
                  "list",
                  "left-bold",
                  "right-bold",
                  "up-bold",
                  "down-bold",
                  "user-add",
                  "help-circled",
                  "info-circled",
                  "eye",
                  "tag",
                  "upload-cloud",
                  "reply",
                  "reply-all",
                  "code",
                  "export",
                  "print",
                  "retweet",
                  "comment",
                  "chat",
                  "vcard",
                  "address",
                  "location",
                  "map",
                  "compass",
                  "trash",
                  "doc",
                  "doc-text-inv",
                  "docs",
                  "doc-landscape",
                  "archive",
                  "rss",
                  "share",
                  "basket",
                  "shareable",
                  "login",
                  "logout",
                  "volume",
                  "resize-full",
                  "resize-small",
                  "popup",
                  "publish",
                  "window",
                  "arrow-combo",
                  "chart-pie",
                  "language",
                  "air",
                  "database",
                  "drive",
                  "bucket",
                  "thermometer",
                  "down-circled",
                  "left-circled",
                  "right-circled",
                  "up-circled",
                  "down-open",
                  "left-open",
                  "right-open",
                  "up-open",
                  "down-open-mini",
                  "left-open-mini",
                  "right-open-mini",
                  "up-open-mini",
                  "down-open-big",
                  "left-open-big",
                  "right-open-big",
                  "up-open-big",
                  "progress-0",
                  "progress-1",
                  "progress-2",
                  "progress-3",
                  "back-in-time",
                  "network",
                  "inbox",
                  "install",
                  "lifebuoy",
                  "mouse",
                  "dot",
                  "dot-2",
                  "dot-3",
                  "suitcase",
                  "flow-cascade",
                  "flow-branch",
                  "flow-tree",
                  "flow-line",
                  "flow-parallel",
                  "brush",
                  "paper-plane",
                  "magnet",
                  "gauge",
                  "traffic-cone",
                  "cc",
                  "cc-by",
                  "cc-nc",
                  "cc-nc-eu",
                  "cc-nc-jp",
                  "cc-sa",
                  "cc-nd",
                  "cc-pd",
                  "cc-zero",
                  "cc-share",
                  "cc-remix",
                  "github",
                  "github-circled",
                  "flickr",
                  "flickr-circled",
                  "vimeo",
                  "vimeo-circled",
                  "twitter",
                  "twitter-circled",
                  "facebook",
                  "facebook-circled",
                  "facebook-squared",
                  "gplus",
                  "gplus-circled",
                  "pinterest",
                  "pinterest-circled",
                  "tumblr",
                  "tumblr-circled",
                  "linkedin",
                  "linkedin-circled",
                  "dribbble",
                  "dribbble-circled",
                  "stumbleupon",
                  "stumbleupon-circled",
                  "lastfm",
                  "lastfm-circled",
                  "rdio",
                  "rdio-circled",
                  "spotify",
                  "spotify-circled",
                  "qq",
                  "instagram",
                  "dropbox",
                  "evernote",
                  "flattr",
                  "skype",
                  "skype-circled",
                  "renren",
                  "sina-weibo",
                  "paypal",
                  "picasa",
                  "soundcloud",
                  "mixi",
                  "behance",
                  "google-circles",
                  "vkontakte",
                  "smashing",
                  "db-shape",
                  "sweden",
                  "logo-db",
                  "picture",
                  "globe",
                  "leaf",
                  "graduation-cap",
                  "mic",
                  "palette",
                  "ticket",
                  "video",
                  "target",
                  "music",
                  "trophy",
                  "thumbs-up",
                  "thumbs-down",
                  "bag",
                  "user",
                  "users",
                  "lamp",
                  "alert",
                  "water",
                  "droplet",
                  "credit-card",
                  "monitor",
                  "briefcase",
                  "floppy",
                  "cd",
                  "folder",
                  "doc-text",
                  "calendar",
                  "chart-line",
                  "chart-bar",
                  "clipboard",
                  "attach",
                  "bookmarks",
                  "book",
                  "book-open",
                  "phone",
                  "megaphone",
                  "upload",
                  "download",
                  "box",
                  "newspaper",
                  "mobile",
                  "signal",
                  "camera",
                  "shuffle",
                  "loop",
                  "arrows-ccw",
                  "light-down",
                  "light-up",
                  "mute",
                  "sound",
                  "battery",
                  "search",
                  "key",
                  "lock",
                  "lock-open",
                  "bell",
                  "bookmark",
                  "link",
                  "back",
                  "flashlight",
                  "chart-area",
                  "clock",
                  "rocket",
                  "block",
                  //Font Awesome
                  "glass",
                  "music",
                  "search",
                  "envelope",
                  "heart",
                  "star",
                  "star-empty",
                  "user",
                  "film",
                  "th-large",
                  "th",
                  "th-list",
                  "ok",
                  "remove",
                  "zoom-in",
                  "zoom-out",
                  "off",
                  "signal",
                  "cog",
                  "trash",
                  "home",
                  "file",
                  "time",
                  "road",
                  "download-alt",
                  "download",
                  "upload",
                  "inbox",
                  "play-circle",
                  "repeat",
                  "refresh",
                  "list-alt",
                  "lock",
                  "flag",
                  "headphones",
                  "volume-off",
                  "volume-down",
                  "volume-up",
                  "qrcode",
                  "barcode",
                  "tag",
                  "tags",
                  "book",
                  "bookmark",
                  "print",
                  "camera",
                  "font",
                  "bold",
                  "italic",
                  "text-height",
                  "text-width",
                  "align-left",
                  "align-center",
                  "align-right",
                  "align-justify",
                  "list",
                  "indent-left",
                  "indent-right",
                  "facetime-video",
                  "picture",
                  "pencil",
                  "map-marker",
                  "adjust",
                  "tint",
                  "edit",
                  "share",
                  "check",
                  "move",
                  "step-backward",
                  "fast-backward",
                  "backward",
                  "play",
                  "pause",
                  "stop",
                  "forward",
                  "fast-forward",
                  "step-forward",
                  "eject",
                  "chevron-left",
                  "chevron-right",
                  "plus-sign",
                  "minus-sign",
                  "remove-sign",
                  "ok-sign",
                  "question-sign",
                  "info-sign",
                  "screenshot",
                  "remove-circle",
                  "ok-circle",
                  "ban-circle",
                  "arrow-left",
                  "arrow-right",
                  "arrow-up",
                  "arrow-down",
                  "share-alt",
                  "resize-full",
                  "resize-small",
                  "plus",
                  "minus",
                  "asterisk",
                  "exclamation-sign",
                  "gift",
                  "leaf",
                  "fire",
                  "eye-open",
                  "eye-close",
                  "warning-sign",
                  "plane",
                  "calendar",
                  "random",
                  "comment",
                  "magnet",
                  "chevron-up",
                  "chevron-down",
                  "retweet",
                  "shopping-cart",
                  "folder-close",
                  "folder-open",
                  "resize-vertical",
                  "resize-horizontal",
                  "bar-chart",
                  "twitter-sign",
                  "facebook-sign",
                  "camera-retro",
                  "key",
                  "cogs",
                  "comments",
                  "thumbs-up",
                  "thumbs-down",
                  "star-half",
                  "heart-empty",
                  "signout",
                  "linkedin-sign",
                  "pushpin",
                  "external-link",
                  "signin",
                  "trophy",
                  "github-sign",
                  "upload-alt",
                  "lemon",
                  "phone",
                  "check-empty",
                  "bookmark-empty",
                  "phone-sign",
                  "twitter",
                  "facebook",
                  "github",
                  "unlock",
                  "credit-card",
                  "rss",
                  "hdd",
                  "bullhorn",
                  "bell",
                  "certificate",
                  "hand-right",
                  "hand-left",
                  "hand-up",
                  "hand-down",
                  "circle-arrow-left",
                  "circle-arrow-right",
                  "circle-arrow-up",
                  "circle-arrow-down",
                  "globe",
                  "wrench",
                  "tasks",
                  "filter",
                  "briefcase",
                  "fullscreen",
                  "group",
                  "link",
                  "cloud",
                  "beaker",
                  "cut",
                  "copy",
                  "paper-clip",
                  "save",
                  "sign-blank",
                  "reorder",
                  "list-ul",
                  "list-ol",
                  "strikethrough",
                  "underline",
                  "table",
                  "magic",
                  "truck",
                  "pinterest",
                  "pinterest-sign",
                  "google-plus-sign",
                  "google-plus",
                  "money",
                  "caret-down",
                  "caret-up",
                  "caret-left",
                  "caret-right",
                  "columns",
                  "sort",
                  "sort-down",
                  "sort-up",
                  "envelope-alt",
                  "linkedin",
                  "undo",
                  "legal",
                  "dashboard",
                  "comment-alt",
                  "comments-alt",
                  "bolt",
                  "sitemap",
                  "umbrella",
                  "paste",
                  "lightbulb",
                  "exchange",
                  "cloud-download",
                  "cloud-upload",
                  "user-md",
                  "stethoscope",
                  "suitcase",
                  "bell-alt",
                  "coffee",
                  "food",
                  "file-alt",
                  "building",
                  "hospital",
                  "ambulance",
                  "medkit",
                  "fighter-jet",
                  "beer",
                  "h-sign",
                  "plus-sign-alt",
                  "double-angle-left",
                  "double-angle-right",
                  "double-angle-up",
                  "double-angle-down",
                  "angle-left",
                  "angle-right",
                  "angle-up",
                  "angle-down",
                  "desktop",
                  "laptop",
                  "tablet",
                  "mobile-phone",
                  "circle-blank",
                  "quote-left",
                  "quote-right",
                  "spinner",
                  "circle",
                  "reply",
                  "github-alt",
                  "folder-close-alt",
                  "folder-open-alt",
                   "user",
                  "film",
                  "th-large"
                )
            )
        );

	    // allow the theme or other plugins to "hook" into this shorcode's params
	    $this->params = apply_filters('pixcodes_filter_params_for_' . strtolower($this->name), $this->params);

        add_shortcode('icon', array( $this, 'add_shortcode') );
    }

    public function add_shortcode($atts, $content){

        extract( shortcode_atts( array(
            'name' => '',
            'type' => '',
            'size' => '',
	        'class' => ''
        ), $atts ) );

		// replace the , with a space
	    $classes = explode(',',$class);
	    $class = implode(' ', $classes);
		
		// make sure that there is no icon- in front
		$prefix = 'icon-';
		if (substr($name, 0, strlen($prefix)) == $prefix) {
			$name = substr($name, strlen($prefix));
		}

	    /**
	     * Template localization between plugin and theme
	     */
	    $located = locate_template("templates/shortcodes/{$this->code}.php", false, false);
	    if(!$located) {
		    $located = dirname(__FILE__).'/templates/'.$this->code.'.php';
	    }
	    // load it
	    ob_start();
	    require $located;
	    return ob_get_clean();
    }
}
